fixed download link
summernote/summernote.github.io pull request #64
Opened 2020-08-30 13:07 UTC by easylogic

This is to change main dowload link  to  https://github.com/summernote/summernote/releases/download/v0.8.18/summernote-0.8.18-dist.zip

2020-08-30 13:21 UTC, DiemenDesign commented
Is there a download of master that we can reference so we don't have to update this link with new releases?

2020-08-30 13:27 UTC, easylogic commented
@DiemenDesign   

No,  master branch is not exists currently. 

I think we should be update download link when a new release occurs .

2020-08-30 13:35 UTC, DiemenDesign approved these changes

2020-11-27 08:18 UTC, hackerwins requested changes
Thanks for your contribution. I left a comment.

2020-11-27 08:18 UTC, hackerwins commented on index.html
> +    <a href="{{ site.repository }}/releases/download/v0.8.18/summernote-0.8.18-dist.zip" class="index-download">
I would like to change it as below.
```suggestion
    "{{ site.repository }}/releases/download/v{{ site.version }}/summernote-{{ site.version }}-dist.zip"
```

2020-11-27 09:29 UTC, easylogic commented on index.html
> +    <a href="{{ site.repository }}/releases/download/v0.8.18/summernote-0.8.18-dist.zip" class="index-download">
Good comment.

2020-11-27 19:10 UTC, hackerwins approved these changes
LGTM~ Thanks for contributing.

2020-11-27 19:11 UTC, merged